jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |-
            ./logger.sh Submission-OpenMusic-v3.0 & pid=$!
             iostat -d sda 1 >> logs/io.temp & iopid=$!
            cd Submission-OpenMusic-v3.0
            git pull origin master
            npm install
            pm2 restart sss
             kill $iopid
             kill $pid
             cd ..
             ./io_logger.sh Submission-OpenMusic-v3.0
          username: ${{ secrets.SSH_USERNAME }}
name: Continuous Deployment
'on':
  push:
    branches:
      - master
